#!/bin/bash
fliter_optimize_rod_loads.py -optimize -resonator_fname sdof_dist_params_nphi1_nr5.json5 -loading_fname_mod loading0200_sdof_dist_oar15.dat
fliter_optimize_rod_loads.py -optimize -resonator_fname sdof_dist_params_nphi1_nr15.json5 -loading_fname_mod loading0200_sdof_dist_oar15.dat
fliter_optimize_rod_loads.py -optimize -resonator_fname sdof_dist_params_nphi2_nr10.json5 -loading_fname_mod loading0200_sdof_dist_oar15.dat
fliter_optimize_rod_loads.py -optimize -resonator_fname sdof_dist_params_nphi4_nr10.json5 -loading_fname_mod loading0200_sdof_dist_oar15.dat
fliter_optimize_rod_loads.py -optimize -resonator_fname sdof_dist_params_nphi1_nr10_staggered.json5 -loading_fname_mod loading0200_sdof_dist_oar15.dat
fliter_optimize_rod_loads.py -optimize -resonator_fname sdof_dist_params_nphi2_nr10_staggered.json5 -loading_fname_mod loading0200_sdof_dist_oar15.dat
fliter_optimize_rod_loads.py -optimize -resonator_fname sdof_dist_params_nphi4_nr10_staggered.json5 -loading_fname_mod loading0200_sdof_dist_oar15.dat
fliter_optimize_rod_loads.py -optimize -resonator_fname sdof_dist_params_nphi1_nr10_staggered_2.json5 -loading_fname_mod loading0200_sdof_dist_oar15.dat
fliter_optimize_rod_loads.py -optimize -resonator_fname sdof_dist_params_nphi2_nr10_staggered_2.json5 -loading_fname_mod loading0200_sdof_dist_oar15.dat
fliter_optimize_rod_loads.py -optimize -resonator_fname sdof_dist_params_nphi4_nr10_staggered_2.json5 -loading_fname_mod loading0200_sdof_dist_oar15.dat
